export const CONFIG = Object.freeze({
  TICK_MS: 100,
  TICK_SECONDS: 0.1,
  MATCH_SECONDS: 720,
  WORLD_LENGTH: 24000,
  SQUAD_COUNT: 25,
  MEMBERS_PER_SQUAD: 4,
  PLAYER_SQUAD_ID: 0,
  DECISION_TIMEOUT_TICKS: 100,
  VIEW_WORLD_WIDTH: 2500,
  MAX_RENDERED_SQUADS: 10,
  COMBAT_GRACE_TICKS: 180,
  SIMULATION_VERSION: 2,
  MAP_VERSION: 2,
  LOOT_VERSION: 1,
  RULES_VERSION: 1
});
