export class EffectsRenderer {
  constructor(container){this.container=container;this.g=new PIXI.Graphics();container.addChild(this.g);}
  render(sim,camera,w,groundY,scale=1){const g=this.g;g.clear();
    for(const smoke of sim.utilitySystem.smokes){const x=camera.worldToScreenX(smoke.x,w);if(x<-300||x>w+300)continue;const grow=Math.min(1,(sim.tick-smoke.createdTick)/18),life=Math.min(1,(smoke.expiresTick-sim.tick)/20),radius=smoke.radius*scale*(.45+grow*.55);for(let i=0;i<9;i++){const phase=i*2.399+sim.tick*.012,orbit=radius*(.18+(i%4)*.12);g.circle(x+Math.cos(phase)*orbit,groundY-(42+Math.sin(phase*.8)*22)*scale,radius*(.27+(i%3)*.055)).fill({color:i%2?0xc8d0d2:0xaebbc0,alpha:.075*life});}g.ellipse(x,groundY-8*scale,radius*.72,radius*.13).fill({color:0x91a1a4,alpha:.08*life});}
    for(const barrier of sim.utilitySystem.barriers){const x=camera.worldToScreenX(barrier.x,w);if(x<0||x>w)continue;const pulse=.55+Math.sin(sim.tick*.22)*.12,hp=Math.max(.15,barrier.hp/90);g.roundRect(x-39*scale,groundY-53*scale,78*scale,53*scale,12*scale).stroke({color:0x78d9ee,width:Math.max(2,5*scale),alpha:.13*pulse});g.roundRect(x-35*scale,groundY-49*scale,70*scale,49*scale,9*scale).fill({color:0x315765,alpha:.28}).stroke({color:hp<.35?0xff8b72:0xa9ebf7,width:Math.max(1,2*scale),alpha:.75});for(let i=-1;i<=1;i++)g.moveTo(x+i*20*scale,groundY-46*scale).lineTo(x+i*20*scale,groundY-5*scale).stroke({color:0xb7eff8,width:Math.max(1,scale),alpha:.22});}
    for(const e of sim.visualEvents){const age=sim.tick-e.tick;if(e.type==='shot'&&age<3){const x1=camera.worldToScreenX(e.fromX,w),x2=camera.worldToScreenX(e.toX,w),fade=1-age/3,y1=groundY-42*scale,y2=groundY-(e.hit?45:30)*scale;g.moveTo(x1,y1).lineTo(x2,y2).stroke({color:e.weapon==='dmr'?0xffe7a0:0xffc45b,width:Math.max(1,1.5*scale),alpha:.62*fade});g.circle(x1,y1,5*scale*fade).fill({color:0xffe4a1,alpha:.7*fade});if(e.hit){g.circle(x2,y2,6*scale*fade).stroke({color:0xff796c,width:Math.max(1,2*scale),alpha:.8*fade});}}
      else if(e.type==='explosion'&&age<8){const x=camera.worldToScreenX(e.x,w),p=age/8,r=(18+p*72)*scale;g.circle(x,groundY-25*scale,r).stroke({color:0xff9a4b,width:Math.max(1,(6-age*.6)*scale),alpha:(1-p)*.75});g.circle(x,groundY-25*scale,r*.55).fill({color:0xffd27b,alpha:(1-p)*.24});for(let i=0;i<7;i++){const a=i*.9;g.circle(x+Math.cos(a)*r,groundY-25*scale+Math.sin(a)*r*.55,Math.max(1,3*scale*(1-p))).fill({color:0xffc46b,alpha:1-p});}}
      else if((e.type==='heal'||e.type==='boost')&&age<12){const x=camera.worldToScreenX(e.x,w),p=age/12,color=e.type==='heal'?0x78e6a1:0x70cfff,y=groundY-(45+p*45)*scale;g.circle(x,y,14*scale*(1-p*.4)).stroke({color,width:Math.max(1,2*scale),alpha:1-p});g.moveTo(x-6*scale,y).lineTo(x+6*scale,y).moveTo(x,y-6*scale).lineTo(x,y+6*scale).stroke({color,width:Math.max(1,2*scale),alpha:1-p});}
      else if((e.type==='smokePop'||e.type==='barrierPop')&&age<7){const x=camera.worldToScreenX(e.x,w),p=age/7;g.circle(x,groundY-20*scale,(15+p*48)*scale).stroke({color:e.type==='smokePop'?0xd7e0e2:0x8ce7f5,width:Math.max(1,3*scale),alpha:(1-p)*.5});}}
  }
}
