import { Camera } from './Camera.js';
import { CharacterRenderer } from './CharacterRenderer.js';
import { EffectsRenderer } from './EffectsRenderer.js';
import { CONFIG } from '../config.js';

export class WorldRenderer {
  constructor(host){this.host=host;this.app=new PIXI.Application();this.camera=new Camera();this.viewScale=1;this.desktopTransparent=false;this.backgroundAlpha=.92;this.staticLayer=new PIXI.Container();this.effectLayer=new PIXI.Container();this.characterLayer=new PIXI.Container();this.overlayLayer=new PIXI.Container();this.characterRenderer=new CharacterRenderer(this.characterLayer);this.effects=new EffectsRenderer(this.effectLayer);this.ready=false;}
  async init(){await this.app.init({resizeTo:this.host,backgroundAlpha:0,antialias:true,resolution:Math.min(2,window.devicePixelRatio||1),autoDensity:true});this.host.appendChild(this.app.canvas);this.app.stage.addChild(this.staticLayer,this.effectLayer,this.characterLayer,this.overlayLayer);this.ready=true;}
  setViewScale(value){this.viewScale=Math.max(.7,Math.min(1.5,Number(value)||1));this.camera.viewWidth=CONFIG.VIEW_WORLD_WIDTH/this.viewScale;}
  setDesktopVisuals({transparent=false,backgroundAlpha=.92}={}){this.desktopTransparent=!!transparent;const parsed=Number(backgroundAlpha);this.backgroundAlpha=Math.max(0,Math.min(1,Number.isFinite(parsed)?parsed:.92));}
  render(sim,dt){if(!this.ready||!sim)return;const w=this.app.screen.width,h=this.app.screen.height,groundY=Math.max(280,h*.73);this.camera.follow(sim.playerSquad.x,dt);this.drawWorld(sim,w,h,groundY);this.effects.render(sim,this.camera,w,groundY);const entries=[];const squads=[sim.playerSquad,...sim.squads.filter(s=>s.id!==0&&!s.isEliminated&&this.camera.visible(s.x,w)).sort((a,b)=>Math.abs(a.x-sim.playerSquad.x)-Math.abs(b.x-sim.playerSquad.x)).slice(0,CONFIG.MAX_RENDERED_SQUADS-1)];for(const squad of squads){const sx=this.camera.worldToScreenX(squad.x,w);squad.members.forEach((member,i)=>{if(member.state==='dead'&&squad.id!==0)return;entries.push({member,x:sx+(i-1.5)*34,enemy:squad.id!==0});});}
    this.characterRenderer.render(entries,dt,groundY,Math.max(.72,Math.min(1.15,w/1200)));}
  drawWorld(sim,w,h,groundY){for(const child of this.staticLayer.removeChildren())child.destroy?.({children:true});const bg=new PIXI.Graphics();const panelAlpha=this.desktopTransparent?0:Math.max(.08,this.backgroundAlpha);bg.rect(0,0,w,h).fill({color:0x101923,alpha:panelAlpha});bg.rect(0,groundY,w,h-groundY).fill({color:0x1e2d29,alpha:this.desktopTransparent ? .28 : Math.max(.35,this.backgroundAlpha)});bg.rect(0,groundY-5,w,6).fill({color:0x40574c,alpha:this.desktopTransparent ? .55 : 1});this.staticLayer.addChild(bg);
    const far=new PIXI.Graphics();for(let i=0;i<9;i++){const x=(i*190-(this.camera.centerX*.035)%190);far.moveTo(x,groundY).lineTo(x+95,groundY-90-(i%3)*18).lineTo(x+190,groundY).fill({color:0x172630,alpha:this.desktopTransparent ? .25 : .7});}this.staticLayer.addChild(far);
    for(const poi of sim.lootSystem.pois){if(!this.camera.visible(poi.x,w,160))continue;const x=this.camera.worldToScreenX(poi.x,w);const g=new PIXI.Graphics();const width=poi.type==='warehouse'?120:poi.type==='apartments'?82:64;const height=poi.type==='apartments'?120:poi.type==='warehouse'?72:58;g.roundRect(x-width/2,groundY-height,width,height,6).fill({color:poi.type==='garage'?0x5e625d:0x394550,alpha:.9}).stroke({color:0x6f7f86,width:2});g.rect(x-10,groundY-28,20,28).fill(0x1c252c);this.staticLayer.addChild(g);const label=new PIXI.Text({text:poi.name,style:{fill:0xb9c6cc,fontSize:10,fontFamily:'Arial'}});label.anchor.set(.5,1);label.position.set(x,groundY-height-5);this.staticLayer.addChild(label);}
    const red=new PIXI.Graphics();const leftX=this.camera.worldToScreenX(sim.zone.left,w),rightX=this.camera.worldToScreenX(sim.zone.right,w);if(leftX>0)red.rect(0,0,Math.min(w,leftX),h).fill({color:0x9e2222,alpha:.17});if(rightX<w)red.rect(Math.max(0,rightX),0,w-Math.max(0,rightX),h).fill({color:0x9e2222,alpha:.17});red.rect(leftX-2,0,4,h).fill({color:0xff4d4d,alpha:.85});red.rect(rightX-2,0,4,h).fill({color:0xff4d4d,alpha:.85});this.staticLayer.addChild(red);
    for(const v of sim.vehicleSystem.vehicles){if(v.destroyed||v.claimedBy!=null||!this.camera.visible(v.x,w,100))continue;const x=this.camera.worldToScreenX(v.x,w),g=new PIXI.Graphics();g.roundRect(x-32,groundY-24,64,20,7).fill(0x73664f).stroke({color:0x22272a,width:2});g.circle(x-20,groundY-3,8).fill(0x202326);g.circle(x+20,groundY-3,8).fill(0x202326);this.staticLayer.addChild(g);}}
  destroy(){this.characterRenderer.destroy();this.app.destroy(true,{children:true});}
}
