import { Camera } from './Camera.js';
import { CharacterRenderer } from './CharacterRenderer.js';
import { EffectsRenderer } from './EffectsRenderer.js';
import { CONFIG } from '../config.js';

export class WorldRenderer {
  constructor(host){this.host=host;this.app=new PIXI.Application();this.camera=new Camera();this.viewScale=1;this.desktopTransparent=false;this.backgroundAlpha=.92;this.staticLayer=new PIXI.Container();this.effectLayer=new PIXI.Container();this.characterLayer=new PIXI.Container();this.overlayLayer=new PIXI.Container();this.characterRenderer=new CharacterRenderer(this.characterLayer);this.effects=new EffectsRenderer(this.effectLayer);this.ready=false;}
  async init(){await this.app.init({resizeTo:this.host,backgroundAlpha:0,antialias:true,resolution:Math.min(2,window.devicePixelRatio||1),autoDensity:true});this.host.appendChild(this.app.canvas);this.app.stage.addChild(this.staticLayer,this.effectLayer,this.characterLayer,this.overlayLayer);this.ready=true;}
  setViewScale(value){this.viewScale=Math.max(.2,Math.min(1.25,Number(value)||.85));this.camera.zoom=this.viewScale;this.camera.viewWidth=CONFIG.VIEW_WORLD_WIDTH/this.viewScale;}
  setDesktopVisuals({transparent=false,backgroundAlpha=.92}={}){this.desktopTransparent=!!transparent;const parsed=Number(backgroundAlpha);this.backgroundAlpha=Math.max(0,Math.min(1,Number.isFinite(parsed)?parsed:.92));}
  render(sim,dt){if(!this.ready||!sim)return;const w=this.app.screen.width,h=this.app.screen.height,groundY=Math.max(170,h*.73),worldScale=this.viewScale*Math.max(.7,Math.min(1.1,w/1200));this.camera.follow(sim.playerSquad.x,dt);this.drawWorld(sim,w,h,groundY,worldScale);this.effects.render(sim,this.camera,w,groundY,worldScale);const squads=[sim.playerSquad,...sim.squads.filter(s=>s.id!==0&&!s.isEliminated&&this.camera.visible(s.x,w)).sort((a,b)=>Math.abs(a.x-sim.playerSquad.x)-Math.abs(b.x-sim.playerSquad.x)).slice(0,CONFIG.MAX_RENDERED_SQUADS-1)];this.drawCombatClarity(sim,squads,w,groundY,worldScale);const entries=[];for(const squad of squads){squad.members.forEach(member=>{if(member.state==='dead')return;entries.push({member,x:this.camera.worldToScreenX(squad.x+member.offsetX,w),enemy:squad.id!==0});});}
    this.characterRenderer.render(entries,dt,groundY,worldScale*.82);}
  drawCombatClarity(sim,squads,w,groundY,scale){for(const child of this.overlayLayer.removeChildren())child.destroy?.({children:true});const shown=new Set(squads.map(s=>s.id)),g=new PIXI.Graphics();for(let i=0;i<squads.length;i++)for(let j=i+1;j<squads.length;j++){const a=squads[i],b=squads[j];if(!shown.has(a.id)||!shown.has(b.id)||Math.abs(a.x-b.x)>950)continue;const ax=this.camera.worldToScreenX(a.x,w),bx=this.camera.worldToScreenX(b.x,w),y=groundY-92*scale;g.moveTo(ax,y).lineTo(bx,y).stroke({color:(a.id===0||b.id===0)?0xffc55c:0xb65a57,width:Math.max(1,2*scale),alpha:(a.id===0||b.id===0)?.62:.2});g.circle(ax,y,3*scale).fill({color:0xffc55c,alpha:.8});g.circle(bx,y,3*scale).fill({color:0xff6b62,alpha:.8});}this.overlayLayer.addChild(g);for(const squad of squads){const x=this.camera.worldToScreenX(squad.x,w),contact=sim.nearbyEnemies(squad,950).length>0;const label=new PIXI.Text({text:squad.id===0?'YOUR SQUAD':contact?`${squad.name}  • ENGAGED`:squad.name,style:{fill:squad.id===0?0xaee6ff:contact?0xffaaa3:0x9aa8ad,fontSize:Math.max(7,10*scale),fontWeight:'700',fontFamily:'Arial'}});label.anchor.set(.5,1);label.position.set(x,groundY-104*scale);this.overlayLayer.addChild(label);}}
  drawWorld(sim,w,h,groundY,scale){for(const child of this.staticLayer.removeChildren())child.destroy?.({children:true});const bg=new PIXI.Graphics();const panelAlpha=this.desktopTransparent?0:Math.max(.08,this.backgroundAlpha);bg.rect(0,0,w,h).fill({color:0x101923,alpha:panelAlpha});bg.rect(0,groundY,w,h-groundY).fill({color:0x1e2d29,alpha:this.desktopTransparent ? .28 : Math.max(.35,this.backgroundAlpha)});bg.rect(0,groundY-5*scale,w,Math.max(2,6*scale)).fill({color:0x40574c,alpha:this.desktopTransparent ? .55 : 1});this.staticLayer.addChild(bg);
    const far=new PIXI.Graphics(),ridgeStep=Math.max(55,190*scale),ridgeCount=Math.ceil(w/ridgeStep)+2;for(let i=-1;i<ridgeCount;i++){const x=i*ridgeStep-(this.camera.centerX*.035*scale)%ridgeStep;far.moveTo(x,groundY).lineTo(x+ridgeStep*.5,groundY-(90+(i%3)*18)*scale).lineTo(x+ridgeStep,groundY).fill({color:0x172630,alpha:this.desktopTransparent ? .25 : .7});}this.staticLayer.addChild(far);
    for(const poi of sim.lootSystem.pois){if(!this.camera.visible(poi.x,w,160))continue;const x=this.camera.worldToScreenX(poi.x,w);const g=new PIXI.Graphics();const width=(poi.type==='warehouse'?120:poi.type==='apartments'?82:64)*scale;const height=(poi.type==='apartments'?120:poi.type==='warehouse'?72:58)*scale;g.roundRect(x-width/2,groundY-height,width,height,6*scale).fill({color:poi.type==='garage'?0x5e625d:0x394550,alpha:.9}).stroke({color:0x6f7f86,width:Math.max(1,2*scale)});g.rect(x-10*scale,groundY-28*scale,20*scale,28*scale).fill(0x1c252c);this.staticLayer.addChild(g);const label=new PIXI.Text({text:poi.name,style:{fill:0xb9c6cc,fontSize:Math.max(7,10*scale),fontFamily:'Arial'}});label.anchor.set(.5,1);label.position.set(x,groundY-height-5*scale);this.staticLayer.addChild(label);}
    const red=new PIXI.Graphics();const leftX=this.camera.worldToScreenX(sim.zone.left,w),rightX=this.camera.worldToScreenX(sim.zone.right,w);if(leftX>0)red.rect(0,0,Math.min(w,leftX),h).fill({color:0x9e2222,alpha:.17});if(rightX<w)red.rect(Math.max(0,rightX),0,w-Math.max(0,rightX),h).fill({color:0x9e2222,alpha:.17});red.rect(leftX-2,0,4,h).fill({color:0xff4d4d,alpha:.85});red.rect(rightX-2,0,4,h).fill({color:0xff4d4d,alpha:.85});this.staticLayer.addChild(red);
    for(const v of sim.vehicleSystem.vehicles){if(v.destroyed||v.claimedBy!=null||!this.camera.visible(v.x,w,100))continue;const x=this.camera.worldToScreenX(v.x,w),g=new PIXI.Graphics();g.roundRect(x-32*scale,groundY-24*scale,64*scale,20*scale,7*scale).fill(0x73664f).stroke({color:0x22272a,width:Math.max(1,2*scale)});g.circle(x-20*scale,groundY-3*scale,8*scale).fill(0x202326);g.circle(x+20*scale,groundY-3*scale,8*scale).fill(0x202326);this.staticLayer.addChild(g);}}
  destroy(){this.characterRenderer.destroy();this.app.destroy(true,{children:true});}
}
